name: Deploy application

on:
  push:
    branches:
      - '**'
      
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
      
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }} 

jobs:
  build_vault_secret:
    runs-on: ubuntu-latest
    env:      
      DOCKER_IMAGE: jiahao19971/vault-secrets
      
    steps:    
    - name: Checkout the code       
      uses: actions/checkout@v2   
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Prepare           
      id: prepare      
      run: |   
        TAG=$(echo $GITHUB_SHA | head -c7)     
        echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}        
        echo ::set-output name=docker_image::${DOCKER_REGISTRY}/${DOCKER_IMAGE}        
        echo ::set-output name=version::${GITHUB_RUN_NUMBER}  

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
      with:
        install: true

    - name: Docker Login      
      if: success()      
      run: |        
        echo "${DOCKER_PASSWORD}" | docker login ${DOCKER_REGISTRY} --username "${DOCKER_USERNAME}" --password-stdin  
    
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        # Key is named differently to avoid collision
        key: ${{ runner.os }}-vault-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-vault

    - name: Build vault image
      uses: docker/build-push-action@v2
      with:
        context: vault
        builder: ${{ steps.buildx.outputs.name }}
        file: Dockerfile
        target: deploy
        push: true # This would be set to true in a real world deployment scenario.
        tags: ${{ steps.prepare.outputs.docker_image }}:latest
        platforms: ${{ steps.prepare.outputs.docker_platform }}
        cache-from: type=local,src=/tmp/.buildx-cache
          # Note the mode=max here
          # More: https://github.com/moby/buildkit#--export-cache-options
          # And: https://github.com/docker/buildx#--cache-tonametypetypekeyvalue
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
    
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache